"use client";

import { ReactNode } from "react";

interface ReportLayoutProps {
  children: ReactNode;
  headerTitle: string;
  classification?: string;
  dateStr?: string;
}

/**
 * ReportLayout wraps the entire report.
 * It provides standard A4/Letter padding and `@media print` utilities.
 */
export function ReportLayout({ children, headerTitle, classification = "CONFIDENTIAL", dateStr = new Date().toLocaleDateString() }: ReportLayoutProps) {
  return (
    <div className="min-h-screen bg-zinc-100 text-black font-sans print:bg-white flex flex-col items-center py-8 print:py-0">
      
      {/* 
        This is a hidden-on-screen block that only shows when printing.
        It serves as a repeating header across print pages if supported by the browser. 
      */}
      <div className="hidden print:block fixed top-0 left-0 right-0 h-16 pt-4 px-8 border-b border-zinc-200 bg-white z-50">
        <div className="flex justify-between items-end pb-2">
          <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">{headerTitle}</span>
          <div className="flex gap-4">
            <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">{dateStr}</span>
            <span className="text-[10px] font-bold text-red-700 uppercase tracking-widest">{classification}</span>
          </div>
        </div>
      </div>

      <div className="hidden print:block fixed bottom-0 left-0 right-0 h-12 pb-4 px-8 bg-white z-50">
        <div className="flex justify-between items-start pt-2 border-t border-zinc-200">
          <span className="text-[9px] font-medium text-zinc-400 uppercase tracking-widest">Generated by Decidr Enterprise</span>
          <span className="text-[9px] font-medium text-zinc-400 uppercase tracking-widest">Page <span className="pageNumber"></span></span>
        </div>
      </div>

      {/* Main Document Body */}
      <div className="w-full max-w-[850px] bg-white shadow-2xl print:shadow-none print:max-w-none print:w-full">
        {children}
      </div>

      {/* Print Instructions Banner (visible only on screen) */}
      <div className="fixed bottom-0 left-0 right-0 bg-zinc-900 text-white p-4 print:hidden flex items-center justify-between z-50">
        <div className="max-w-[850px] mx-auto w-full flex items-center justify-between">
          <div>
            <h4 className="text-[13px] font-bold uppercase tracking-widest mb-1">Print Mode Active</h4>
            <p className="text-[12px] text-zinc-400">Use Ctrl+P or Cmd+P to save as PDF. Ensure "Background Graphics" is enabled.</p>
          </div>
          <button 
            onClick={() => window.print()}
            className="bg-white text-black px-6 py-2 rounded-md text-[13px] font-bold shadow-lg hover:bg-zinc-200 transition-colors"
          >
            Save as PDF
          </button>
        </div>
      </div>
    </div>
  );
}
